#

lang_text = """
[de]
par01 = Erstellt Kubernetes Projecte für Services
par02 = Schreibe eine Beispiel Config in ein angegebenes File 
par03 = Interpretirt das angegebenen Config File 
par04 = Generirt das Project 
par05 = Gibt bei Fehlermeldungen Programzeile  local Variable und Config-Object aus 
par06 = Gibt alle Config Sectoren mit ihren Optionen und deren Spezivikationen aus 
par07 = Löscht das Project aber nicht Namespace und persistent Volume 
par08 = Löscht das ganze Project 
main01 = Config nicht korrect 
main02 = Kein Kubernetes gefunden 
main03 = Fehler beim Erstellen 
main04 = Fehler beim Patchen 
vol01 = Drive Divice nicht unterstützt 
vol02 = Kann Drive Definition nicht finden 
vol03 = Volume Config fehlerhaft 
cla01 = Kann name oder volume für Claim nicht finden 
cla02 = Kann accessmodes für Claim nicht finden 
cla03 = Kann requests für Claim nicht finden 
cla04 = Konnte Claim kein volume_class zuweisen 
dep01 = Deploy ohne Template macht keinen Sinn 
tem01 = Kein Label für das Template angegeben 
tem02 = Tamplate ohne Container macht keinen Sinn 
tem03 = Kann Claim zum Template-Volume nicht finden 
tem04 = Kann Claim zum Template-Volume nicht finden 
tem05 = label in template mus ein Wort oder ein Wort Paar sein 
con01 = Kein Container für das Template gefunden 
con02 = Container ohne Image macht kein Sinn 
con03 = Kann Volume Claim für Container nicht finden 
sec01 = Secret Type nicht unterstützt 
sec02 = Kann Secret Type Definition nicht finden 
sec03 = Fehler in Secret Type Definition 
s_s01 = Kann tls_key nicht in secret finden 
s_s02 = Kann tls_crt nicht in secret finden 
s_s03 = Kann angegebene Datei nicht finden 
ser01 = Service ohne Template macht keinen Sinn 
ser02 = Keine port Angabe in service oder container Definition gefunden 
ser03 = keine Port Definition gefunden 
ser04 = Keine port_target option in service gefunden 
ser05 = Kann Ports nicht finden 
ser06 = Template angabe in Service fehlerhaft 
ing01 = Kann service oder rule zu ssl-Backend nicht finden 
ing02 = Ingress braucht etwerder einen Rule Host oder ein Backend Host 
ing03 = Kann Eintrag zu Annotation nicht finden 
ing04 = Kann Service zu Ingress Rule nicht finden 
ing05 = Kann Secret zu Ingress tls nicht finden 
ing06 = Kann Port zu Rule nicht finden
cfg01 = Optional
cfg02 = Scalierbar
cfg03 = Options Type
cfg04 = Text
cfg05 = Zahl
cfg06 = Zahlen
cfg07 = Verzeichnis Pfad
cfg08 = Liste
cfg09 = endet mit
cfg10 = oder Verweis
cfg11 = Optional heist das entweder die Option nicht zwingend benötigt wird für das Opject oder das die Option aus einer anderen Option übernommen oder ersetzt werden kann sovern diese vorhanden ist.
"""
